export const CURRENT_PLAN_VERSION = 9;

export const STORAGE_KEY = "life-compass-plan-v1";
export const RECOVERY_STORAGE_KEY = "life-compass-recovery-v2";
export const MAX_RECOVERY_BACKUPS = 3;
export const MAX_IMPORT_FILE_BYTES = 5 * 1024 * 1024;
export const MAX_CLOUD_BACKUP_PLAINTEXT_BYTES = 5 * 1024 * 1024;
export const MAX_SHARED_PLAN_PLAINTEXT_BYTES = 5 * 1024 * 1024;
export const MAX_CLOUD_BACKUPS = 5;
export const MAX_PLAN_REVISIONS = 8;
export const MAX_HOUSEHOLD_MEMBERS = 20;
export const MAX_DETAILED_CASHFLOW_ITEMS = 200;
export const LOCAL_STORAGE_GUIDE_BYTES = 5 * 1024 * 1024;
export const LOCAL_STORAGE_WARNING_BYTES = 3 * 1024 * 1024;
export const MAX_PLAN_AGE = 120;
export const MAX_PLAN_YEAR = 2300;
export const MAX_PROJECTION_YEARS = 80;
export const MAX_RATE_PERCENT = 100;
export const MAX_MONEY_AMOUNT = 1_000_000_000_000_000;
